### ISSUE TITLE
Problemas ao utilizar o pipeline no container do singularity

### ISSUE THREAD

**Issue by grazLet** [dezordi/IAM_SARSCOV2#17]
Olá, estou utilizando o viralflow no container do singularity v.3.8.6 e testando com os arquivos da pasta test_files. 

A etapa de build do container rodou tranquilamente com o comando: 

_conda run -n viralflow viralflow --build -singFilePath ./Singularityfile_ 

Depois utilizei o comando _conda run -n viralflow viralflow --runContainer -inArgsFile ./test_files/test_args.conf_

Após utilizar a linha de comando acima as pastas Cneg.results, ART1.results e ART2.results são criadas, bem como outros arquivos dentro das pastas. Porém o script aparentemente entra em loop e não termina nunca, estou há 2 horas aguardando e nada de finalizar o processo. 

Outro problema que surgiu é um erro muito parecido com outro já levantado em outra questão. No arquivo de erros Cneg_4_pangolin_err.log

Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 1 (use --cores to define parallelism)
Rules claiming more threads will be scaled down.
Traceback (most recent call last):
  File "/home/lacen/.local/lib/python3.8/site-packages/snakemake/__init__.py", line 733, in snakemake
    success = workflow.execute(
  File "/home/lacen/.local/lib/python3.8/site-packages/snakemake/workflow.py", line 1031, in execute
    logger.run_info("\n".join(dag.stats()))
  File "/home/lacen/.local/lib/python3.8/site-packages/snakemake/dag.py", line 2415, in stats
    yield tabulate(rows, headers="keys")
  File "/home/lacen/.local/lib/python3.8/site-packages/tabulate/__init__.py", line 2048, in tabulate
    list_of_lists, headers = _normalize_tabular_data(
  File "/home/lacen/.local/lib/python3.8/site-packages/tabulate/__init__.py", line 1471, in _normalize_tabular_data
    rows = list(map(lambda r: r if _is_separating_line(r) else list(r), rows))
  File "/home/lacen/.local/lib/python3.8/site-packages/tabulate/__init__.py", line 1471, in <lambda>
    rows = list(map(lambda r: r if _is_separating_line(r) else list(r), rows))
  File "/home/lacen/.local/lib/python3.8/site-packages/tabulate/__init__.py", line 107, in _is_separating_line
    (len(row) >= 1 and row[0] == SEPARATING_LINE)
  File "/home/lacen/.local/lib/python3.8/site-packages/snakemake/rules.py", line 1222, in __eq__
    return self.name == other.name and self.output == other.output
AttributeError: 'str' object has no attribute 'name'

Obrigada e aguardo retorno.

**Comment by dezordi** [comment]
Olá, você pode testar implementando a versão v0.1.0 ?

**Comment by dezordi** [comment]
Solved on https://github.com/dezordi/ViralFlow/pull/40
